import 'package:flutter/material.dart';
import 'package:flutter_phoenix/flutter_phoenix.dart';
import 'package:travia/Helpers/AppColors.dart';

BoxDecoration backGroundColor() {
  return BoxDecoration(color: Colors.white);
}

String baseUrlForPlanner = 'http://192.168.8.17:8001';
String baseUrlForClassification = 'http://192.168.8.17:8000';

Future<void> refresh(context) async {
  await Future.delayed(Duration(milliseconds: 300));
  Phoenix.rebirth(context);
}

final List<Map<String, String>> countries = [
  {'code': 'EG', 'name': 'Egypt', 'emoji': '🇪🇬'},
  {'code': 'SA', 'name': 'Saudi Arabia', 'emoji': '🇸🇦'},
  {'code': 'LY', 'name': 'Libya', 'emoji': '🇱🇾'},
  {'code': 'BH', 'name': 'Bahrain', 'emoji': '🇧🇭'},
  {'code': 'FR', 'name': 'France', 'emoji': '🇫🇷'},
  {'code': 'DE', 'name': 'Germany', 'emoji': '🇩🇪'},
  {'code': 'US', 'name': 'United States', 'emoji': '🇺🇸'},
  {'code': 'GB', 'name': 'United Kingdom', 'emoji': '🇬🇧'},
  {'code': 'IT', 'name': 'Italy', 'emoji': '🇮🇹'},
  {'code': 'CZ', 'name': 'Czech Republic', 'emoji': '🇨🇿'},
  {'code': 'CO', 'name': 'Colombia', 'emoji': '🇨🇴'},
  {'code': 'CA', 'name': 'Canada', 'emoji': '🇨🇦'},
  {'code': 'MX', 'name': 'Mexico', 'emoji': '🇲🇽'},
  {'code': 'ES', 'name': 'Spain', 'emoji': '🇪🇸'},
  {'code': 'TN', 'name': 'Tunisia', 'emoji': '🇹🇳'},
  {'code': 'SD', 'name': 'Sudan', 'emoji': '🇸🇩'},
  {'code': 'JO', 'name': 'Jordan', 'emoji': '🇯🇴'},
  {'code': 'KW', 'name': 'Kuwait', 'emoji': '🇰🇼'},
  {'code': 'LB', 'name': 'Lebanon', 'emoji': '🇱🇧'},
  {'code': 'MA', 'name': 'Morocco', 'emoji': '🇲🇦'},
  {'code': 'OM', 'name': 'Oman', 'emoji': '🇴🇲'},
  {'code': 'PS', 'name': 'Palestine, State of', 'emoji': '🇵🇸'},
  {'code': 'QA', 'name': 'Qatar', 'emoji': '🇶🇦'},
  {'code': 'DZ', 'name': 'Algeria', 'emoji': '🇩🇿'},
  {'code': 'SY', 'name': 'Syria', 'emoji': '🇸🇾'},
  {'code': 'IQ', 'name': 'Iraq', 'emoji': '🇮🇶'},
  {'code': 'AE', 'name': 'United Arab Emirates', 'emoji': '🇦🇪'},
  {'code': 'YE', 'name': 'Yemen', 'emoji': '🇾🇪'},
  {'code': 'AF', 'name': 'Afghanistan', 'emoji': '🇦🇫'},
  {'code': 'AX', 'name': 'Åland Islands', 'emoji': '🇦🇽'},
  {'code': 'AL', 'name': 'Albania', 'emoji': '🇦🇱'},
  {'code': 'AS', 'name': 'American Samoa', 'emoji': '🇦🇸'},
  {'code': 'AD', 'name': 'Andorra', 'emoji': '🇦🇩'},
  {'code': 'AO', 'name': 'Angola', 'emoji': '🇦🇴'},
  {'code': 'AI', 'name': 'Anguilla', 'emoji': '🇦🇮'},
  {'code': 'AQ', 'name': 'Antarctica', 'emoji': '🇦🇶'},
  {'code': 'AG', 'name': 'Antigua and Barbuda', 'emoji': '🇦🇬'},
  {'code': 'AR', 'name': 'Argentina', 'emoji': '🇦🇷'},
  {'code': 'AM', 'name': 'Armenia', 'emoji': '🇦🇲'},
  {'code': 'AW', 'name': 'Aruba', 'emoji': '🇦🇼'},
  {'code': 'AU', 'name': 'Australia', 'emoji': '🇦🇺'},
  {'code': 'AT', 'name': 'Austria', 'emoji': '🇦🇹'},
  {'code': 'AZ', 'name': 'Azerbaijan', 'emoji': '🇦🇿'},
  {'code': 'BS', 'name': 'Bahamas', 'emoji': '🇧🇸'},
  {'code': 'BD', 'name': 'Bangladesh', 'emoji': '🇧🇩'},
  {'code': 'BB', 'name': 'Barbados', 'emoji': '🇧🇧'},
  {'code': 'BY', 'name': 'Belarus', 'emoji': '🇧🇾'},
  {'code': 'BE', 'name': 'Belgium', 'emoji': '🇧🇪'},
  {'code': 'BZ', 'name': 'Belize', 'emoji': '🇧🇿'},
  {'code': 'BJ', 'name': 'Benin', 'emoji': '🇧🇯'},
  {'code': 'BM', 'name': 'Bermuda', 'emoji': '🇧🇲'},
  {'code': 'BT', 'name': 'Bhutan', 'emoji': '🇧🇹'},
  {'code': 'BO', 'name': 'Bolivia', 'emoji': '🇧🇴'},
  {'code': 'BA', 'name': 'Bosnia and Herzegovina', 'emoji': '🇧🇦'},
  {'code': 'BW', 'name': 'Botswana', 'emoji': '🇧🇼'},
  {'code': 'BR', 'name': 'Brazil', 'emoji': '🇧🇷'},
  {'code': 'BN', 'name': 'Brunei Darussalam', 'emoji': '🇧🇳'},
  {'code': 'BG', 'name': 'Bulgaria', 'emoji': '🇧🇬'},
  {'code': 'BF', 'name': 'Burkina Faso', 'emoji': '🇧🇫'},
  {'code': 'BI', 'name': 'Burundi', 'emoji': '🇧🇮'},
  {'code': 'CV', 'name': 'Cabo Verde', 'emoji': '🇨🇻'},
  {'code': 'KH', 'name': 'Cambodia', 'emoji': '🇰🇭'},
  {'code': 'CM', 'name': 'Cameroon', 'emoji': '🇨🇲'},
  {'code': 'KY', 'name': 'Cayman Islands', 'emoji': '🇰🇾'},
  {'code': 'CF', 'name': 'Central African Republic', 'emoji': '🇨🇫'},
  {'code': 'TD', 'name': 'Chad', 'emoji': '🇹🇩'},
  {'code': 'CL', 'name': 'Chile', 'emoji': '🇨🇱'},
  {'code': 'CN', 'name': 'China', 'emoji': '🇨🇳'},
  {'code': 'CX', 'name': 'Christmas Island', 'emoji': '🇨🇽'},
  {'code': 'CC', 'name': 'Cocos (Keeling) Islands', 'emoji': '🇨🇨'},
  {'code': 'KM', 'name': 'Comoros', 'emoji': '🇰🇲'},
  {'code': 'CG', 'name': 'Congo', 'emoji': '🇨🇬'},
  {'code': 'CD', 'name': 'Congo, Democratic Republic of the', 'emoji': '🇨🇩'},
  {'code': 'CK', 'name': 'Cook Islands', 'emoji': '🇨🇰'},
  {'code': 'CR', 'name': 'Costa Rica', 'emoji': '🇨🇷'},
  {'code': 'CI', 'name': "Côte d'Ivoire", 'emoji': '🇨🇮'},
  {'code': 'HR', 'name': 'Croatia', 'emoji': '🇭🇷'},
  {'code': 'CU', 'name': 'Cuba', 'emoji': '🇨🇺'},
  {'code': 'CW', 'name': 'Curaçao', 'emoji': '🇨🇼'},
  {'code': 'CY', 'name': 'Cyprus', 'emoji': '🇨🇾'},
  {'code': 'DK', 'name': 'Denmark', 'emoji': '🇩🇰'},
  {'code': 'DJ', 'name': 'Djibouti', 'emoji': '🇩🇯'},
  {'code': 'DM', 'name': 'Dominica', 'emoji': '🇩🇲'},
  {'code': 'DO', 'name': 'Dominican Republic', 'emoji': '🇩🇴'},
  {'code': 'EC', 'name': 'Ecuador', 'emoji': '🇪🇨'},
  {'code': 'SV', 'name': 'El Salvador', 'emoji': '🇸🇻'},
  {'code': 'GQ', 'name': 'Equatorial Guinea', 'emoji': '🇬🇶'},
  {'code': 'EE', 'name': 'Estonia', 'emoji': '🇪🇪'},
  {'code': 'SZ', 'name': 'Eswatini', 'emoji': '🇸🇿'},
  {'code': 'ET', 'name': 'Ethiopia', 'emoji': '🇪🇹'},
  {'code': 'FK', 'name': 'Falkland Islands (Malvinas)', 'emoji': '🇫🇰'},
  {'code': 'FO', 'name': 'Faroe Islands', 'emoji': '🇫🇴'},
  {'code': 'FJ', 'name': 'Fiji', 'emoji': '🇫🇯'},
  {'code': 'FI', 'name': 'Finland', 'emoji': '🇫🇮'},
  {'code': 'PF', 'name': 'French Polynesia', 'emoji': '🇵🇫'},
  {'code': 'TF', 'name': 'French Southern Territories', 'emoji': '🇹🇫'},
  {'code': 'GA', 'name': 'Gabon', 'emoji': '🇬🇦'},
  {'code': 'GM', 'name': 'Gambia', 'emoji': '🇬🇲'},
  {'code': 'GE', 'name': 'Georgia', 'emoji': '🇬🇪'},
  {'code': 'GH', 'name': 'Ghana', 'emoji': '🇬🇭'},
  {'code': 'GI', 'name': 'Gibraltar', 'emoji': '🇬🇮'},
  {'code': 'GR', 'name': 'Greece', 'emoji': '🇬🇷'},
  {'code': 'GL', 'name': 'Greenland', 'emoji': '🇬🇱'},
  {'code': 'GD', 'name': 'Grenada', 'emoji': '🇬🇩'},
  {'code': 'GU', 'name': 'Guam', 'emoji': '🇬🇺'},
  {'code': 'GT', 'name': 'Guatemala', 'emoji': '🇬🇹'},
  {'code': 'GG', 'name': 'Guernsey', 'emoji': '🇬🇬'},
  {'code': 'GN', 'name': 'Guinea', 'emoji': '🇬🇳'},
  {'code': 'GW', 'name': 'Guinea-Bissau', 'emoji': '🇬🇼'},
  {'code': 'GY', 'name': 'Guyana', 'emoji': '🇬🇾'},
  {'code': 'HT', 'name': 'Haiti', 'emoji': '🇭🇹'},
  {'code': 'VA', 'name': 'Holy See', 'emoji': '🇻🇦'},
  {'code': 'HN', 'name': 'Honduras', 'emoji': '🇭🇳'},
  {'code': 'HK', 'name': 'Hong Kong', 'emoji': '🇭🇰'},
  {'code': 'HU', 'name': 'Hungary', 'emoji': '🇭🇺'},
  {'code': 'IS', 'name': 'Iceland', 'emoji': '🇮🇸'},
  {'code': 'IN', 'name': 'India', 'emoji': '🇮🇳'},
  {'code': 'ID', 'name': 'Indonesia', 'emoji': '🇮🇩'},
  {'code': 'IR', 'name': 'Iran', 'emoji': '🇮🇷'},
  {'code': 'IE', 'name': 'Ireland', 'emoji': '🇮🇪'},
  {'code': 'IM', 'name': 'Isle of Man', 'emoji': '🇮🇲'},
  {'code': 'JM', 'name': 'Jamaica', 'emoji': '🇯🇲'},
  {'code': 'JP', 'name': 'Japan', 'emoji': '🇯🇵'},
  {'code': 'JE', 'name': 'Jersey', 'emoji': '🇯🇪'},
  {'code': 'KZ', 'name': 'Kazakhstan', 'emoji': '🇰🇿'},
  {'code': 'KE', 'name': 'Kenya', 'emoji': '🇰🇪'},
  {'code': 'KI', 'name': 'Kiribati', 'emoji': '🇰🇮'},
  {'code': 'KP', 'name': 'North Korea', 'emoji': '🇰🇵'},
  {'code': 'KR', 'name': 'South Korea', 'emoji': '🇰🇷'},
  {'code': 'KG', 'name': 'Kyrgyzstan', 'emoji': '🇰🇬'},
  {'code': 'LA', 'name': 'Laos', 'emoji': '🇱🇦'},
  {'code': 'LV', 'name': 'Latvia', 'emoji': '🇱🇻'},
  {'code': 'LS', 'name': 'Lesotho', 'emoji': '🇱🇸'},
  {'code': 'LR', 'name': 'Liberia', 'emoji': '🇱🇷'},
  {'code': 'LI', 'name': 'Liechtenstein', 'emoji': '🇱🇮'},
  {'code': 'LT', 'name': 'Lithuania', 'emoji': '🇱🇹'},
  {'code': 'LU', 'name': 'Luxembourg', 'emoji': '🇱🇺'},
  {'code': 'MO', 'name': 'Macao', 'emoji': '🇲🇴'},
  {'code': 'MG', 'name': 'Madagascar', 'emoji': '🇲🇬'},
  {'code': 'MW', 'name': 'Malawi', 'emoji': '🇲🇼'},
  {'code': 'MY', 'name': 'Malaysia', 'emoji': '🇲🇾'},
  {'code': 'MV', 'name': 'Maldives', 'emoji': '🇲🇻'},
  {'code': 'ML', 'name': 'Mali', 'emoji': '🇲🇱'},
  {'code': 'MT', 'name': 'Malta', 'emoji': '🇲🇹'},
  {'code': 'MH', 'name': 'Marshall Islands', 'emoji': '🇲🇭'},
  {'code': 'MQ', 'name': 'Martinique', 'emoji': '🇲🇶'},
  {'code': 'MR', 'name': 'Mauritania', 'emoji': '🇲🇷'},
  {'code': 'MU', 'name': 'Mauritius', 'emoji': '🇲🇺'},
  {'code': 'YT', 'name': 'Mayotte', 'emoji': '🇾🇹'},
  {'code': 'FM', 'name': 'Micronesia', 'emoji': '🇫🇲'},
  {'code': 'MD', 'name': 'Moldova', 'emoji': '🇲🇩'},
  {'code': 'MC', 'name': 'Monaco', 'emoji': '🇲🇨'},
  {'code': 'MN', 'name': 'Mongolia', 'emoji': '🇲🇳'},
  {'code': 'ME', 'name': 'Montenegro', 'emoji': '🇲🇪'},
  {'code': 'MS', 'name': 'Montserrat', 'emoji': '🇲🇸'},
  {'code': 'MZ', 'name': 'Mozambique', 'emoji': '🇲🇿'},
  {'code': 'MM', 'name': 'Myanmar', 'emoji': '🇲🇲'},
  {'code': 'NA', 'name': 'Namibia', 'emoji': '🇳🇦'},
  {'code': 'NR', 'name': 'Nauru', 'emoji': '🇳🇷'},
  {'code': 'NP', 'name': 'Nepal', 'emoji': '🇳🇵'},
  {'code': 'NL', 'name': 'Netherlands', 'emoji': '🇳🇱'},
  {'code': 'NC', 'name': 'New Caledonia', 'emoji': '🇳🇨'},
  {'code': 'NZ', 'name': 'New Zealand', 'emoji': '🇳🇿'},
  {'code': 'NI', 'name': 'Nicaragua', 'emoji': '🇳🇮'},
  {'code': 'NE', 'name': 'Niger', 'emoji': '🇳🇪'},
  {'code': 'NG', 'name': 'Nigeria', 'emoji': '🇳🇬'},
  {'code': 'NU', 'name': 'Niue', 'emoji': '🇳🇺'},
  {'code': 'NF', 'name': 'Norfolk Island', 'emoji': '🇳🇫'},
  {'code': 'MK', 'name': 'North Macedonia', 'emoji': '🇲🇰'},
  {'code': 'MP', 'name': 'Northern Mariana Islands', 'emoji': '🇲🇵'},
  {'code': 'NO', 'name': 'Norway', 'emoji': '🇳🇴'},
  {'code': 'PK', 'name': 'Pakistan', 'emoji': '🇵🇰'},
  {'code': 'PW', 'name': 'Palau', 'emoji': '🇵🇼'},
  {'code': 'PA', 'name': 'Panama', 'emoji': '🇵🇦'},
  {'code': 'PG', 'name': 'Papua New Guinea', 'emoji': '🇵🇬'},
  {'code': 'PY', 'name': 'Paraguay', 'emoji': '🇵🇾'},
  {'code': 'PE', 'name': 'Peru', 'emoji': '🇵🇪'},
  {'code': 'PH', 'name': 'Philippines', 'emoji': '🇵🇭'},
  {'code': 'PN', 'name': 'Pitcairn', 'emoji': '🇵🇳'},
  {'code': 'PL', 'name': 'Poland', 'emoji': '🇵🇱'},
  {'code': 'PT', 'name': 'Portugal', 'emoji': '🇵🇹'},
  {'code': 'PR', 'name': 'Puerto Rico', 'emoji': '🇵🇷'},
  {'code': 'RE', 'name': 'Réunion', 'emoji': '🇷🇪'},
  {'code': 'RO', 'name': 'Romania', 'emoji': '🇷🇴'},
  {'code': 'RU', 'name': 'Russia', 'emoji': '🇷🇺'},
  {'code': 'RW', 'name': 'Rwanda', 'emoji': '🇷🇼'},
  {'code': 'SH', 'name': 'Saint Helena, Ascension and Tristan da Cunha', 'emoji': '🇸🇭'},
  {'code': 'KN', 'name': 'Saint Kitts and Nevis', 'emoji': '🇰🇳'},
  {'code': 'LC', 'name': 'Saint Lucia', 'emoji': '🇱🇨'},
  {'code': 'MF', 'name': 'Saint Martin (French part)', 'emoji': '🇲🇫'},
  {'code': 'VC', 'name': 'Saint Vincent and the Grenadines', 'emoji': '🇻🇨'},
  {'code': 'WS', 'name': 'Samoa', 'emoji': '🇼🇸'},
  {'code': 'SM', 'name': 'San Marino', 'emoji': '🇸🇲'},
  {'code': 'ST', 'name': 'Sao Tome and Principe', 'emoji': '🇸🇹'},
  {'code': 'SN', 'name': 'Senegal', 'emoji': '🇸🇳'},
  {'code': 'RS', 'name': 'Serbia', 'emoji': '🇷🇸'},
  {'code': 'SC', 'name': 'Seychelles', 'emoji': '🇸🇨'},
  {'code': 'SL', 'name': 'Sierra Leone', 'emoji': '🇸🇱'},
  {'code': 'SG', 'name': 'Singapore', 'emoji': '🇸🇬'},
  {'code': 'SK', 'name': 'Slovakia', 'emoji': '🇸🇰'},
  {'code': 'SI', 'name': 'Slovenia', 'emoji': '🇸🇮'},
  {'code': 'SB', 'name': 'Solomon Islands', 'emoji': '🇸🇧'},
  {'code': 'SO', 'name': 'Somalia', 'emoji': '🇸🇴'},
  {'code': 'ZA', 'name': 'South Africa', 'emoji': '🇿🇦'},
  {'code': 'GS', 'name': 'South Georgia and the South Sandwich Islands', 'emoji': '🇬🇸'},
  {'code': 'LK', 'name': 'Sri Lanka', 'emoji': '🇱🇰'},
  {'code': 'SR', 'name': 'Suriname', 'emoji': '🇸🇷'},
  {'code': 'SE', 'name': 'Sweden', 'emoji': '🇸🇪'},
  {'code': 'CH', 'name': 'Switzerland', 'emoji': '🇨🇭'},
  {'code': 'TW', 'name': 'Taiwan', 'emoji': '🇹🇼'},
  {'code': 'TJ', 'name': 'Tajikistan', 'emoji': '🇹🇯'},
  {'code': 'TZ', 'name': 'Tanzania', 'emoji': '🇹🇿'},
  {'code': 'TH', 'name': 'Thailand', 'emoji': '🇹🇭'},
  {'code': 'TL', 'name': 'Timor-Leste', 'emoji': '🇹🇱'},
  {'code': 'TG', 'name': 'Togo', 'emoji': '🇹🇬'},
  {'code': 'TK', 'name': 'Tokelau', 'emoji': '🇹🇰'},
  {'code': 'TO', 'name': 'Tonga', 'emoji': '🇹🇴'},
  {'code': 'TT', 'name': 'Trinidad and Tobago', 'emoji': '🇹🇹'},
  {'code': 'TR', 'name': 'Turkey', 'emoji': '🇹🇷'},
  {'code': 'TM', 'name': 'Turkmenistan', 'emoji': '🇹🇲'},
  {'code': 'TC', 'name': 'Turks and Caicos Islands', 'emoji': '🇹🇨'},
  {'code': 'TV', 'name': 'Tuvalu', 'emoji': '🇹🇻'},
  {'code': 'UG', 'name': 'Uganda', 'emoji': '🇺🇬'},
  {'code': 'UA', 'name': 'Ukraine', 'emoji': '🇺🇦'},
  {'code': 'UY', 'name': 'Uruguay', 'emoji': '🇺🇾'},
  {'code': 'UZ', 'name': 'Uzbekistan', 'emoji': '🇺🇿'},
  {'code': 'VU', 'name': 'Vanuatu', 'emoji': '🇻🇺'},
  {'code': 'VE', 'name': 'Venezuela', 'emoji': '🇻🇪'},
  {'code': 'VN', 'name': 'Vietnam', 'emoji': '🇻🇳'},
  {'code': 'VG', 'name': 'Virgin Islands (British)', 'emoji': '🇻🇬'},
  {'code': 'VI', 'name': 'Virgin Islands (U.S.)', 'emoji': '🇻🇮'},
  {'code': 'WF', 'name': 'Wallis and Futuna', 'emoji': '🇼🇫'},
  {'code': 'EH', 'name': 'Western Sahara', 'emoji': '🇪🇭'},
  {'code': 'ZM', 'name': 'Zambia', 'emoji': '🇿🇲'},
  {'code': 'ZW', 'name': 'Zimbabwe', 'emoji': '🇿🇼'},
];
String getEmojiFromCountryName(String countryName) {
  return countries.firstWhere(
    (country) => country['name'] == countryName,
    orElse: () => {'emoji': '🏳️'}, // default/fallback emoji
  )['emoji']!;
}

class BadgeStyle {
  final List<Color> gradient;
  final IconData icon;

  const BadgeStyle({required this.gradient, required this.icon});
}

final Map<String, BadgeStyle> badgeStyles = {
  'Founder': BadgeStyle(
    gradient: [Color(0xFF8A2BE2), Color(0xFF4B0082), Color(0xFF9400D3)],
    icon: Icons.verified,
  ),
  'Poster': BadgeStyle(
    gradient: [Colors.blue, Colors.black54],
    icon: Icons.post_add,
  ),
  'Adventurer': BadgeStyle(
    gradient: [Color(0xFF1D976C), Color(0xFF11998E)],
    icon: Icons.explore,
  ),
  'Social': BadgeStyle(
    gradient: [Color(0xFFF46B45), Color(0xFFEEA849)],
    icon: Icons.forum,
  ),
  'Trendy': BadgeStyle(
    gradient: [Color(0xFFFF416C), Color(0xFFFF4B2B)],
    icon: Icons.trending_up,
  ),
  'Ramy': BadgeStyle(
    gradient: [Color(0xFF00C9FF), Colors.blue],
    icon: Icons.local_cafe,
  ),
  'International': BadgeStyle(
    gradient: [Color(0xFF0F2027), Color(0xFF203A43), Color(0xFF2C5364)],
    icon: Icons.public,
  ),
  'Follower': BadgeStyle(
    gradient: [Color(0xFFDA22FF), Color(0xFF9733EE)],
    icon: Icons.people_alt,
  ),
  'Tester': BadgeStyle(
    gradient: [Colors.black, Colors.teal],
    icon: Icons.bug_report,
  ),
  'New User': BadgeStyle(
    gradient: [Color(0xFFFF5F6D), Color(0xFFFFC371)],
    icon: Icons.fiber_new,
  ),
  'Commentator': BadgeStyle(
    gradient: [Color(0xFF0575E6), Color(0xFF021B79)],
    icon: Icons.comment,
  ),
  'Supporter': BadgeStyle(
    gradient: [Color(0xFFFF0000), Color(0xFFF20089)],
    icon: Icons.favorite,
  ),
  'Messenger': BadgeStyle(
    gradient: [Color(0xFF00F260), Color(0xFF0575E6)],
    icon: Icons.message,
  ),
  'Story Star': BadgeStyle(
    gradient: [Color(0xFF834D9B), Color(0xFFD04ED6)],
    icon: Icons.star,
  ),
  'Friendly': BadgeStyle(
    gradient: [Color(0xFF56CCF2), Color(0xFF2F80ED)],
    icon: Icons.group,
  ),
  'Engaged': BadgeStyle(
    gradient: [Color(0xFFFDC830), Color(0xFFF37335)],
    icon: Icons.notifications_active,
  ),
  'Profile Pro': BadgeStyle(
    gradient: [Color(0xFFED213A), Color(0xFF93291E)],
    icon: Icons.person,
  ),
  'Platinum': BadgeStyle(
    gradient: [kDeepPink, Colors.black],
    icon: Icons.military_tech,
  ),
};

final defaultBadgeStyle = BadgeStyle(
  gradient: [Colors.blue, Colors.blue],
  icon: Icons.star_border,
);

const badgeDescriptions = {
  'Founder': 'Reserved for the visionary creator of the app.',
  'Poster': 'Share your voice by posting 5 or more times.',
  'Adventurer': 'Plan 5 or more adventures to earn this badge.',
  'Social': 'Join 5 or more conversations to connect with others.',
  'Trendy': 'Create 3 or more posts, each with 5+ likes.',
  'Ramy': 'Include "Ramy" in your display name to unlock this badge.',
  'International': 'Visit 5 or more countries and add them to your profile.',
  'Follower': 'Build a following of 10 or more users.',
  'Tester': 'Earned by early testers who helped shape the app.',
  'New User': 'Welcome aboard! Engage to earn more badges.',
  'Commentator': 'Leave 10 or more comments.',
  'Supporter': 'Show love by liking 15 or more posts, comments, or stories.',
  'Messenger': 'Send 20 or more messages in general.',
  'Story Star': 'Have your story items viewed 10 or more times.',
  'Friendly': 'Follow 5 users and have the same users follow you back.',
  'Engaged': 'Read 10 or more notifications.',
  'Profile Pro': 'Fully complete your profile with email, name, username, photo, and bio.',
  'Platinum': 'Your reward for earning all badges (except Founder, Tester and Adventurer).',
};
