// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8U6HGiWQjJlYRp5hGsc7XFAGMKIauWbE',
    appId: '1:536970171951:web:754a684ef8223bf8bdd8da',
    messagingSenderId: '536970171951',
    projectId: 'travia-aast-8b14f',
    authDomain: 'travia-aast-8b14f.firebaseapp.com',
    storageBucket: 'travia-aast-8b14f.firebasestorage.app',
    measurementId: 'G-MNSMCNZVN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA88wycgztfXsAXRXTDrrMiGyURs6loWz0',
    appId: '1:536970171951:android:304805a8f5db498dbdd8da',
    messagingSenderId: '536970171951',
    projectId: 'travia-aast-8b14f',
    storageBucket: 'travia-aast-8b14f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_7N10TkKx9U0cpjxr34245tSNKBUrtoU',
    appId: '1:536970171951:ios:36b0044c6a16706cbdd8da',
    messagingSenderId: '536970171951',
    projectId: 'travia-aast-8b14f',
    storageBucket: 'travia-aast-8b14f.firebasestorage.app',
    androidClientId: '536970171951-ho9vqanbr5a486ofp84timva64lmn48r.apps.googleusercontent.com',
    iosClientId: '536970171951-su6g0ahdgf98ha64gsh7f8ski12927o1.apps.googleusercontent.com',
    iosBundleId: 'com.grad.aast',
  );

}