// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgi-BLceMMDlIqqLIwjQ1NsHK8F4OH2JQ',
    appId: '1:1037102746825:web:e3c98fa1e9e44d4d03d118',
    messagingSenderId: '1037102746825',
    projectId: 'travia-aast',
    authDomain: 'travia-aast.firebaseapp.com',
    storageBucket: 'travia-aast.firebasestorage.app',
    measurementId: 'G-77MVS5MSLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ_voI_CGYnlTVAzBC1Vr4ruoIsLfuEmc',
    appId: '1:1037102746825:android:8dd53a78f04d14ae03d118',
    messagingSenderId: '1037102746825',
    projectId: 'travia-aast',
    storageBucket: 'travia-aast.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBImwFEfRbvnRmNdn-gESE79WYQ-HDhf_s',
    appId: '1:1037102746825:ios:9b7c1b014215c3b603d118',
    messagingSenderId: '1037102746825',
    projectId: 'travia-aast',
    storageBucket: 'travia-aast.firebasestorage.app',
    androidClientId: '1037102746825-cep31d6vllovb09d0nivvkkcl26pt9dq.apps.googleusercontent.com',
    iosClientId: '1037102746825-j9t1vnf28qh5fo1kvliita7tuiv3prvt.apps.googleusercontent.com',
    iosBundleId: 'com.aast.travia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBImwFEfRbvnRmNdn-gESE79WYQ-HDhf_s',
    appId: '1:1037102746825:ios:9b7c1b014215c3b603d118',
    messagingSenderId: '1037102746825',
    projectId: 'travia-aast',
    storageBucket: 'travia-aast.firebasestorage.app',
    androidClientId: '1037102746825-cep31d6vllovb09d0nivvkkcl26pt9dq.apps.googleusercontent.com',
    iosClientId: '1037102746825-j9t1vnf28qh5fo1kvliita7tuiv3prvt.apps.googleusercontent.com',
    iosBundleId: 'com.aast.travia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgi-BLceMMDlIqqLIwjQ1NsHK8F4OH2JQ',
    appId: '1:1037102746825:web:e3c98fa1e9e44d4d03d118',
    messagingSenderId: '1037102746825',
    projectId: 'travia-aast',
    authDomain: 'travia-aast.firebaseapp.com',
    storageBucket: 'travia-aast.firebasestorage.app',
    measurementId: 'G-77MVS5MSLF',
  );

}