// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC38kWFtXjqd9GHCgCY2P5cB7i3VGjIfOc',
    appId: '1:560098689683:web:349755ee0f40af9872c366',
    messagingSenderId: '560098689683',
    projectId: 'traviaapp-8bc84',
    authDomain: 'traviaapp-8bc84.firebaseapp.com',
    storageBucket: 'traviaapp-8bc84.firebasestorage.app',
    measurementId: 'G-0HGH9E5PPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR8FrosfC4Nv3trKZVM2yGmoZJ3c9UY3Y',
    appId: '1:560098689683:android:6cc08171c695691d72c366',
    messagingSenderId: '560098689683',
    projectId: 'traviaapp-8bc84',
    storageBucket: 'traviaapp-8bc84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiipa8ZO1iGFUxKpy7msBGSQRhtQTJ0_A',
    appId: '1:560098689683:ios:443691257f0051dd72c366',
    messagingSenderId: '560098689683',
    projectId: 'traviaapp-8bc84',
    storageBucket: 'traviaapp-8bc84.firebasestorage.app',
    iosClientId: '560098689683-lfknimfkqdat2hfrvamsuh9n0di4q4pi.apps.googleusercontent.com',
    iosBundleId: 'com.grad.aast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiipa8ZO1iGFUxKpy7msBGSQRhtQTJ0_A',
    appId: '1:560098689683:ios:030f9cb78eab71bc72c366',
    messagingSenderId: '560098689683',
    projectId: 'traviaapp-8bc84',
    storageBucket: 'traviaapp-8bc84.firebasestorage.app',
    iosClientId: '560098689683-hi8uani9s1na25shuv14nqtfr6gin6o8.apps.googleusercontent.com',
    iosBundleId: 'com.aast.travia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC38kWFtXjqd9GHCgCY2P5cB7i3VGjIfOc',
    appId: '1:560098689683:web:815502b60890425572c366',
    messagingSenderId: '560098689683',
    projectId: 'traviaapp-8bc84',
    authDomain: 'traviaapp-8bc84.firebaseapp.com',
    storageBucket: 'traviaapp-8bc84.firebasestorage.app',
    measurementId: 'G-1PNF6R7L6P',
  );
}
