include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    # Add any custom lint rules here if needed
custom_lint:
  # Forcibly disable lint rules by default
  enable_all_lint_rules: true